name: example

on: 
  push:
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '13', '15' ]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Java ${{ matrix.Java }} sample
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build native with Maven
      run: mvn -B package
